language: python
python: # specify version 
  - "3.6"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame 
script: # specify default build script
  - pytest
