language: python
python: # specify version 
  - "3.6"
before_install: # update the package manager and install pygame
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame
install: # bring pygame into the virtualenv
  - pip install pygame
script: # specify default build script (Unit test files go here as well)
  - python Travis-CI/test.py
