language: python
python: # specify version 
  - "3.6"
before_install: # update the package manager and install pygame
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame
install: # bring pygame into the virtualenv
  - pip install pygame
notifications: # prevent Travis-CI from flooding my inbox
  email:
    on_success: change # when a build changes from broken to fixed
    on_failure: change # when a build changes from working to broken
script: # specify test script
  - pytest
